name: Build Astro docs and check links
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      skipVersionUpdate:
        description: 'Skip updating the version in package.json'
        type: boolean
        required: false
        default: false
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: Update version
        if: ${{ github.event.inputs.skipVersionUpdate != 'true' }}
        run: npm run update-version
      - name: Build with Astro
        if: github.event_name != 'pull_request'
        run: npm run build
      - name: Check links
        if: github.event_name == 'pull_request'
        run: npm run check-links
        env:
          CHECK_LINKS: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist
